# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5d2b021b553180fcf225d8c98f5ee96a2d04c2a443b05b5e07b8867f475820cc76dfa1b79eed3d22e33b48917e31137ac66ae0e2940783308c140b3ae497a1d

test:
  secret_key_base: e372b8435a34eefca3465f4dfb2615ceb74425acbc55a71d2da3408aab54c796b268d4476409ef01af5048047362babc1456ed1e933c9884b3eeafe0954c0d00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
